### ISSUE TITLE
Remove backticks from mermaid code

### ISSUE THREAD

**Issue by sanketshevkar** [accordproject/concerto#665] opened 2023-07-07 10:18 UTC
# Bug Report 🐛

The mermaid code generation results in a correct expected code, but with backticks around properties and their types.

## Expected Behavior

```
classDiagram
class `mermaid@1.0.0.Person` {
<< concept>>
   + String id
}

class `mermaid@1.0.0.Company` {
<< concept>>
   + String name
}
```
[Link](https://mermaid.live/edit#pako:eNqFUE1LAzEQ_SvhXQ2lqaVbQymCXgWhN8mhQxLbYDNZsllwXfa_m9a9eBCZw8ybmffmY4RNzkPDXqjrngOdMkXDNySO0edIwT2qxbLaq89d4qMYDe92wia2vi37vWEhxJ04lBz4JIIzPBn-Q-IpxZZ4-EeDKfqqAomZXfcbry0G5exrDbqGjvKHwU8f9SUdBrbQJfdeom8dFT-fA_1Ol65m6-i3lH5h6BGf0EuJAVrdL9abjXrYrpvVtlGrZpL4uhGUhHehpPwyf-vqpm9a1WfK)

## Current Behavior

```
classDiagram
class `mermaid@1.0.0.Person` {
<< concept>>
   + `String` `id`
}

class `mermaid@1.0.0.Company` {
<< concept>>
   + `String` `name`
}
```
[Link](https://mermaid.live/edit#pako:eNqFkE1rwzAMhv-K0XWm1F1pOlPKYLsOBr0NHyxsrTWr5eA4sCzkv8_pctlhDB2kV0iPPkZwyRNocFfsuueA54zR8E0JGylHDP5RrdbVXil3ia0YDR8OwiV21Jbj0bAQ4k7YU8mBz1bY4K3hyfAfmKcUW-Thfw5jpJkEEhZC3XOcywyUC0UyoGvoMX8Y-KnDvqTTwA50yT1J6FuPhZazQL_jtavZOv4tpV8a9AifoNcSBtDqfrXd7dTDftts9o3aNJOEr1uDkkA-lJRflq_NbvoG_uJqyg)

**Comment by shubhalgupta** [comment] 2023-09-10 12:21
please assign this to me!

**Comment by shubhalgupta** [comment] 2023-09-10 12:26
![Screenshot (570)](https://github.com/accordproject/concerto/assets/107386458/375a226a-5435-420c-af95-30ad5d1ccc16)

**Comment by shubhalgupta** [comment] 2023-09-10 12:26
How to save and do a PR? @sanketshevkar

**Comment by sanketshevkar** [comment] 2023-09-10 14:36
You can refer to [this](https://github.com/accordproject/techdocs/blob/main/CONTRIBUTING.md#-pull-request-submission-guidelines). Also please make a fork of this repo.

**Comment by sanketshevkar** [comment] 2023-09-10 14:37
Also which repo have you made the changes? @shubhalgupta

**Comment by shubhalgupta** [comment] 2023-09-10 15:37
@sanketshevkar I am raising a PR and I made changes just to the link you provided!

**Comment by shubhalgupta** [comment] 2023-09-10 16:05
@sanketshevkar in which repo is the mermaid code?

**Comment by shubhalgupta** [comment] 2023-09-10 16:19
@sanketshevkar I am not getting the mermaid code, can you please where is it present?

**Comment by sanketshevkar** [comment] 2023-09-11 16:12
> @sanketshevkar I am raising a PR and I made changes just to the link you provided!

The link I provided is just a reference to code-generation output we are expecting.

**Comment by sanketshevkar** [comment] 2023-09-11 16:19
> @sanketshevkar I am not getting the mermaid code, can you please where is it present? but I have got mermaid visitor file.

There is no mermaid code as such. The mermaid code is a result of code generation that happens using the mermaid visitor in the codegen repo I suggested you to clone yesterday.
The model is converted to mermaid code. Please refer to docs. This shall help you.
https://concerto.accordproject.org/docs/reference/codegen/codegen-mermaid
https://concerto.accordproject.org/docs/reference/codegen/codegen-create-new

**Comment by Shubham1450** [comment] 2023-10-21 06:06
I want to contribute but not able to find the code.
please help! @sanketshevkar

**Comment by sanketshevkar** [comment] 2023-10-25 09:27
@Shubham1450 , bug might somewhere here. https://github.com/accordproject/concerto-codegen/blob/main/lib/codegen/fromcto/mermaid/mermaidvisitor.js
Please do investigation from your side.

**Comment by Shubham1450** [comment] 2023-10-25 12:58
@sanketshevkar  how to set up this project locally.

**Comment by subhajit20** [comment] 2024-02-24 16:55
hey @sanketshevkar I have made a pr. Can you check once and let me know if any changes needed.

**Comment by apoorvsxna** [comment] 2024-03-03 22:17
Hi @sanketshevkar. I have managed to fix this issue by modifying the mermaidvisitor.js file located in the concert-codegen repository.

I have understood the contribution guidelines and would like to make a pull request, which I assume I would have to do in the concert-codegen repository (?).

The guidelines indicate that each pull request should link to the issue it closes. However, this particular issue is not listed there. How should I proceed?

**Comment by sanketshevkar** [comment] 2024-03-04 07:57
Hi @apoorvsxna 
I believe @subhajit20 has PR up for review already. If you'd still like to contribute, you can review @subhajit20's PR and offer some suggestions if you'd have any.
Let's not duplicate our efforts.

Coming back to attaching a ticket, you can create a new ticket on codegen repo and link it here. And also link it in your PR.

**Comment by Thanush19** [comment] 2024-08-10 05:51
hey @subhajit20 , if the issue is not fixed  , i can work on this

**Comment by sanketshevkar** [comment] 2024-11-26 04:19
@Thanush19 thanks for your interest. This issue is already fixed. I'll close this issue.

**Closed** 2024-11-26 04:20 UTC
Labels: Good First Issue :octocat:
