### ISSUE TITLE
Add support for class diagram relationships in PlantUML generation.

### ISSUE THREAD

**Issue by davidoevans** [accordproject/concerto#166] opened 2020-02-05 18:33 UTC
**Is your feature request related to a problem? Please describe.**
The current PlantUMLVisitor implementation does not represent `-->` relationships defined in a concerto model.

**Describe the solution you'd like**
PlantUML generated would show class diagram relationships for property references modelled as `-->` as documented here -> [Class Diagrams Relationships](https://plantuml.com/class-diagram).

**Describe alternatives you've considered**
When introducing this feature, consider having it be an option that can be passed via `parameters` since these relationships may appear cluttered for more complex models.

**Additional context**
@dselman pointed to this line of code as likely being best place to implement this feature. -> https://github.com/accordproject/concerto/blob/master/packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js#L220

**Comment by Aniruddha-Shriwant** [comment] 2021-03-27 08:45
@mttrbrts ,
I was willing to work on this but was having some doubts,
https://github.com/accordproject/concerto/blob/c2ecad3e5d52b0e8b1c7caf026d62abbf4f68b6f/packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js#L220-L222

As you can see here it uses `-->` when it extends superClass/has any superClass i.e. it shows the relationship...

Also, I was exploring the Accord Project's models repo and found that the same [plantumlvisitor.js](https://github.com/accordproject/concerto/blob/c2ecad3e5d52b0e8b1c7caf026d62abbf4f68b6f/packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js) is used for generating plantUML diagrams that are in html files for models
https://github.com/accordproject/models/blob/c614455d42d61cd3c18f30a6d60b7fe38f9a375c/build.js#L55

So now when you open a model page (for example open this: https://models.accordproject.org/cicero/runtime.html)
You can see the plantUML diagram is showing the relationships between the classes 

So is this issue still open?

Correct me if I'm wrong...I may be wrong :)
If the issue is still open can you throw some light on which `class diagram relationships in PlantUML generation` is @davidoevans  talking about...

**Comment by Aniruddha-Shriwant** [comment] 2021-03-27 14:56
Also @mttrbrts, I was having some doubts regarding plantuml generation,
Although the same `plantumlvisitor.js` is used in `concerto-cli` and `https://github.com/accordproject/models`

 I had used `concerto-cli` command for generating plantuml as follows:
 `concerto compile --ctoFiles calendar.cto --target PlantUML `
 The output plantuml was [this](http://www.plantuml.com/plantuml/png/j9PHSoCr3CVV-ody24Cl3moFDnsMf6LwSxdBqBGyC3mejcvZy5fRMSwnm7rtsCH9kovRxp7NfrXQIzR_9zcJxuC0IspScLXnUBOaW-uClJcOsa48YhYUWTR4fcNw3RNCDX1mLeM0ebw_LbzLvpKZ-g_LnONww-pJys4hOB7Qjk0FmQjpP-kjR5p4QGdM33w05aj-ds1ztg5pz355AwM-KJV2rjTA7hPUcyEN1GYkRODAR8D1e6bBvrtkq4kM67lV_qgfmQ4tmBDvMiofQScZpr7cMg8r_wRzh8IlNlrzyMptobNUUdiVSMADl_ogG0IzGSpScfe6lMIyZEnf3MGIr-3jdyXP1iRxY45k12G634Cqx38q1HKPc3BACgYVK4Vkg_aiLg2ts8C9EIyGh8bj9dHVnRfhd-Br0bf2nbSpWg0Pf30ODDjMBFbijuCWIpBsWps6N7l16bcrR8cjT4zQua3olQ7lazSuE3J4fW7kyYOL2UPzAlIrtAMxoW4tXPi6_PvAdn0bV-fNtwwHeGy5qf6XjvH9Yo4vnXP1fdFBDBt0JDzTxaRcEBl6wCs8n6phQUCFH0x1AnigvnQGHkj7f3aH6-j1CAWQQO33aKv9ipaC55bZUFhsjy3eTVVaJ2rsXptMelWSQtbg9t2zOiHD3Dq4j460PHpuoPVlIxIJnb8XBt3Jtb1a3-u__o1CYNiHy6ioL8IkgMaT2kQ8JSJnAPy-lTdRYgpHopoTEMsqoL1FiIJq2o8Ks-1iILwsUtoNFRxkCRqtu2DmkcbNkE47QmcijuTbrR9rHs-N8gF7uyebNnNh62I9nbQmsI0VpFTQw6IyezsZJmlK1-lJypeMq8seM98tnxhM4SF9-1cDVsIkjv4Vh2ksf_KDIEG7A_RvIlMiiMc9mTrwAoE51TJaJHg3nleec8mjHKvB0rrQVKJyFHGn7CSudV6MVAsWeUWJ-K5TqLifPLmXMpBZCl8Aavn-hDBwFW8BSh8w10xJ3XqLaMgQ8A56ccLtE2LTKH1mbJ6C8IZO_mwlPFBD-tEFSx-Wk76eqE5kptdWTI1Mei6XatozznQgN3dGEBsu3OFNspaP7BW_m1_lOhezvUUhThG1zpOzOYdmyOO6sbjs0vSDLeUxxmO-GOVjbdn9OqAP_JVpq2GHwNklwlhcVUNQBNohgEsB0pSXTnuxCh7LFopGGNQ48104qBEDWeWAHD1n9lS_I1Rvgx_fwbUl0YCN9cOUB6mysJbuyUR33t__dLwS61YvC75bviQ3XPMD9pi7Bxxvy4izvnTd1YvCN9cvys1XPMFdpJSVVlYbNY5ouyx2HlTnPcJYoiv1-ooP6tSMDigd5oS6HYvCN9bviB3oXoSx1o_UV6YtTMTXPUT5-HmOUR2mil5avw2_MsHXunzBT93W80W40V1jn20Q1GsWnFt_G_PIfxfe3psZrnQPk71bPk79oi67xhu7lZXnvSRAniwBD-Ndm8blHivCNBXnPsRXmPDVLZPsNhmv-ED3-oY14oDd9gxSUV1avKNvXpvdOEJCn8KRTsOMLZPs3khtDQz67coywByM-EB4DoCJ5wxySEFEpCA3bOsTDtzyQ9zzufip4nT-k75dPk71oiwRW-PVWOcPZGzzVmTEZ4nSMUWkOwRS9zBx_W8pn__mj0MWZIKzb2OKMekZk0JOKIo1og78581rWHeH6CB-QMcPoQbE-V065cPJCIWr7Tmcn9G1jR5oWCDj-1gOjLmEm3uSSE0U0000) 
 
 But when you will see the plantuml for the same model here https://models.accordproject.org/calendar/calendar.html it will be different (not drastically different but small in size)
 
 So why this is done differently? Are they different because we want small-size plantuml on the website and the rest of the things can be included in the Dependencies section?

**Comment by jeromesimeon** [comment] 2021-04-13 11:05
@Aniruddha-Shriwant I believe the issue is for relationships (`has a`) rather than inheritance (`is a`) https://stackoverflow.com/questions/49002/prefer-composition-over-inheritance

**Comment by Aniruddha-Shriwant** [comment] 2021-04-13 13:34
Thanks @jeromesimeon, for clearing my doubts I will look into it now :)

**Comment by Aaditya-23** [comment] 2021-11-10 19:52
Is this issue still open? If yes then please assign it to me.

**Comment by jeromesimeon** [comment] 2021-11-10 20:14
@Aaditya-23 done.

**Comment by Aaditya-23** [comment] 2021-11-11 06:59
@jeromesimeon thanks for assigning the issue. I had some doubts though. I forked the project concerto repo and cloned it into my pc. But, how do I run the project? Where can I see the plant uml generator?

**Comment by Aaditya-23** [comment] 2021-11-11 07:10
Hey @Aniruddha-Shriwant can your help me out👆?

**Closed** 2023-01-24 14:14 UTC
Labels: Type: Feature Request 🛍️, Good First Issue :octocat:, Difficulty: Starter
