### ISSUE TITLE
Concept validation results in "instance undefined" error message

### ISSUE THREAD

**Issue by sstone1** [accordproject/concerto#330] opened 2021-09-02 09:15 UTC
If I validate an instance of a concept, which does not have an identifier, then the error message is wrong: `Instance undefined missing required field value2`

The `undefined` is probably the identifier which doesn't exist?

**Comment by OmkarAcharekar** [comment] 2022-01-18 06:32
Hey, @sstone1 , I would like to work on this issue. Can you please assign this to me and explain little bit more about this issue?

**Comment by dhruv-joshi-7** [comment] 2022-01-25 04:37
@OmkarAcharekar have you started working on this issue? If yes, can you share what have you done so far so that even I can contribute in solving this issue.

**Comment by tech-bash** [comment] 2022-02-18 17:41
@dselman  sir, I think so its not a bug.

**Closed** 2022-03-01 15:27 UTC
Labels: Type: Bug 🐛, Good First Issue :octocat:
